---
abstract: 'Twitter authentication for Catalyst'
author:
  - 'Jesse Stay <jesse@staynalive.com>'
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
  parent: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Credential-Twitter
provides:
  Catalyst::Authentication::Credential::Twitter:
    file: lib/Catalyst/Authentication/Credential/Twitter.pm
    version: v2.0.0
requires:
  Catalyst::Exception: 0
  Catalyst::Plugin::Session::PerUser: 0
  Class::Accessor::Fast: 0
  Data::Dumper: 0
  Net::Twitter: 4.00001
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Authentication-Credential-Twitter
  homepage: http://search.cpan.org/dist/Catalyst-Authentication-Credential-Twitter/
  repository: https://github.com/yanick/Catalyst-Authentication-Credential-Twitter.git
version: 2.0.0
x_author_pledge:
  version: 1
x_authority: cpan:JESSESTAY
x_contributors:
  - 'Jason McIntosh <jmac@appleseed-sc.com>'
