---
name: Catalyst-Authentication-Credential-Twitter
version: 0.01000
author:
  - 'Jesse Stay (jessestay) <jesse@staynalive.com>'
  - |-
        A SocialToo.com Product
abstract: Twitter authentication module for Catalyst
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBIx::Class: 0.06002
  Net::Twitter: 3.10001
  Catalyst::Plugin::Session::PerUser: 0.04
  Catalyst: 5.80007
provides:
  Catalyst::Authentication::Credential::Twitter:
    file: lib/Catalyst/Authentication/Credential/Twitter.pm
    version: 0.01000
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
