---
abstract: 'Twitter authentication for Catalyst'
author:
  - 'Jesse Stay <jesse@staynalive.com>'
build_requires:
  Carp: 0
  Catalyst: 0
  Catalyst::Controller: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  parent: 0
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Credential-Twitter
provides:
  Catalyst::Authentication::Credential::Twitter:
    file: lib/Catalyst/Authentication/Credential/Twitter.pm
    version: 0.02002
requires:
  Catalyst::Exception: 0
  Class::Accessor::Fast: 0
  Data::Dumper: 0
  Net::Twitter: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Authentication-Credential-Twitter
  homepage: http://search.cpan.org/dist/Catalyst-Authentication-Credential-Twitter/
  repository: https://github.com/yanick/Catalyst-Authentication-Credential-Twitter.git
version: 0.02002
x_authority: cpan:JESSESTAY
